/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.microservices_demo.kafka.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum TweetLabel implements org.apache.avro.generic.GenericEnumSymbol<TweetLabel> {
  HATEFUL, NORMAL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TweetLabel\",\"namespace\":\"com.microservices_demo.kafka.avro.model\",\"symbols\":[\"HATEFUL\",\"NORMAL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
