/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.microservices_demo.kafka.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TweetAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7392591041839524275L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TweetAvroModel\",\"namespace\":\"com.microservices_demo.kafka.avro.model\",\"fields\":[{\"name\":\"tweetId\",\"type\":\"string\"},{\"name\":\"text\",\"type\":\"string\"},{\"name\":\"label\",\"type\":{\"type\":\"enum\",\"name\":\"TweetLabelAvroModel\",\"symbols\":[\"HATEFUL\",\"NORMAL\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TweetAvroModel> ENCODER =
      new BinaryMessageEncoder<TweetAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TweetAvroModel> DECODER =
      new BinaryMessageDecoder<TweetAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TweetAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TweetAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TweetAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TweetAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TweetAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TweetAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TweetAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TweetAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence tweetId;
   private java.lang.CharSequence text;
   private com.microservices_demo.kafka.avro.model.TweetLabelAvroModel label;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TweetAvroModel() {}

  /**
   * All-args constructor.
   * @param tweetId The new value for tweetId
   * @param text The new value for text
   * @param label The new value for label
   */
  public TweetAvroModel(java.lang.CharSequence tweetId, java.lang.CharSequence text, com.microservices_demo.kafka.avro.model.TweetLabelAvroModel label) {
    this.tweetId = tweetId;
    this.text = text;
    this.label = label;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tweetId;
    case 1: return text;
    case 2: return label;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tweetId = (java.lang.CharSequence)value$; break;
    case 1: text = (java.lang.CharSequence)value$; break;
    case 2: label = (com.microservices_demo.kafka.avro.model.TweetLabelAvroModel)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'tweetId' field.
   * @return The value of the 'tweetId' field.
   */
  public java.lang.CharSequence getTweetId() {
    return tweetId;
  }


  /**
   * Sets the value of the 'tweetId' field.
   * @param value the value to set.
   */
  public void setTweetId(java.lang.CharSequence value) {
    this.tweetId = value;
  }

  /**
   * Gets the value of the 'text' field.
   * @return The value of the 'text' field.
   */
  public java.lang.CharSequence getText() {
    return text;
  }


  /**
   * Sets the value of the 'text' field.
   * @param value the value to set.
   */
  public void setText(java.lang.CharSequence value) {
    this.text = value;
  }

  /**
   * Gets the value of the 'label' field.
   * @return The value of the 'label' field.
   */
  public com.microservices_demo.kafka.avro.model.TweetLabelAvroModel getLabel() {
    return label;
  }


  /**
   * Sets the value of the 'label' field.
   * @param value the value to set.
   */
  public void setLabel(com.microservices_demo.kafka.avro.model.TweetLabelAvroModel value) {
    this.label = value;
  }

  /**
   * Creates a new TweetAvroModel RecordBuilder.
   * @return A new TweetAvroModel RecordBuilder
   */
  public static com.microservices_demo.kafka.avro.model.TweetAvroModel.Builder newBuilder() {
    return new com.microservices_demo.kafka.avro.model.TweetAvroModel.Builder();
  }

  /**
   * Creates a new TweetAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TweetAvroModel RecordBuilder
   */
  public static com.microservices_demo.kafka.avro.model.TweetAvroModel.Builder newBuilder(com.microservices_demo.kafka.avro.model.TweetAvroModel.Builder other) {
    if (other == null) {
      return new com.microservices_demo.kafka.avro.model.TweetAvroModel.Builder();
    } else {
      return new com.microservices_demo.kafka.avro.model.TweetAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new TweetAvroModel RecordBuilder by copying an existing TweetAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new TweetAvroModel RecordBuilder
   */
  public static com.microservices_demo.kafka.avro.model.TweetAvroModel.Builder newBuilder(com.microservices_demo.kafka.avro.model.TweetAvroModel other) {
    if (other == null) {
      return new com.microservices_demo.kafka.avro.model.TweetAvroModel.Builder();
    } else {
      return new com.microservices_demo.kafka.avro.model.TweetAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for TweetAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TweetAvroModel>
    implements org.apache.avro.data.RecordBuilder<TweetAvroModel> {

    private java.lang.CharSequence tweetId;
    private java.lang.CharSequence text;
    private com.microservices_demo.kafka.avro.model.TweetLabelAvroModel label;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.microservices_demo.kafka.avro.model.TweetAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tweetId)) {
        this.tweetId = data().deepCopy(fields()[0].schema(), other.tweetId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.text)) {
        this.text = data().deepCopy(fields()[1].schema(), other.text);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.label)) {
        this.label = data().deepCopy(fields()[2].schema(), other.label);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing TweetAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.microservices_demo.kafka.avro.model.TweetAvroModel other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.tweetId)) {
        this.tweetId = data().deepCopy(fields()[0].schema(), other.tweetId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.text)) {
        this.text = data().deepCopy(fields()[1].schema(), other.text);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.label)) {
        this.label = data().deepCopy(fields()[2].schema(), other.label);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'tweetId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTweetId() {
      return tweetId;
    }


    /**
      * Sets the value of the 'tweetId' field.
      * @param value The value of 'tweetId'.
      * @return This builder.
      */
    public com.microservices_demo.kafka.avro.model.TweetAvroModel.Builder setTweetId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.tweetId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'tweetId' field has been set.
      * @return True if the 'tweetId' field has been set, false otherwise.
      */
    public boolean hasTweetId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'tweetId' field.
      * @return This builder.
      */
    public com.microservices_demo.kafka.avro.model.TweetAvroModel.Builder clearTweetId() {
      tweetId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'text' field.
      * @return The value.
      */
    public java.lang.CharSequence getText() {
      return text;
    }


    /**
      * Sets the value of the 'text' field.
      * @param value The value of 'text'.
      * @return This builder.
      */
    public com.microservices_demo.kafka.avro.model.TweetAvroModel.Builder setText(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.text = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'text' field has been set.
      * @return True if the 'text' field has been set, false otherwise.
      */
    public boolean hasText() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'text' field.
      * @return This builder.
      */
    public com.microservices_demo.kafka.avro.model.TweetAvroModel.Builder clearText() {
      text = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'label' field.
      * @return The value.
      */
    public com.microservices_demo.kafka.avro.model.TweetLabelAvroModel getLabel() {
      return label;
    }


    /**
      * Sets the value of the 'label' field.
      * @param value The value of 'label'.
      * @return This builder.
      */
    public com.microservices_demo.kafka.avro.model.TweetAvroModel.Builder setLabel(com.microservices_demo.kafka.avro.model.TweetLabelAvroModel value) {
      validate(fields()[2], value);
      this.label = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'label' field has been set.
      * @return True if the 'label' field has been set, false otherwise.
      */
    public boolean hasLabel() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'label' field.
      * @return This builder.
      */
    public com.microservices_demo.kafka.avro.model.TweetAvroModel.Builder clearLabel() {
      label = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TweetAvroModel build() {
      try {
        TweetAvroModel record = new TweetAvroModel();
        record.tweetId = fieldSetFlags()[0] ? this.tweetId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.text = fieldSetFlags()[1] ? this.text : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.label = fieldSetFlags()[2] ? this.label : (com.microservices_demo.kafka.avro.model.TweetLabelAvroModel) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TweetAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<TweetAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TweetAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<TweetAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.tweetId);

    out.writeString(this.text);

    out.writeEnum(this.label.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.tweetId = in.readString(this.tweetId instanceof Utf8 ? (Utf8)this.tweetId : null);

      this.text = in.readString(this.text instanceof Utf8 ? (Utf8)this.text : null);

      this.label = com.microservices_demo.kafka.avro.model.TweetLabelAvroModel.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.tweetId = in.readString(this.tweetId instanceof Utf8 ? (Utf8)this.tweetId : null);
          break;

        case 1:
          this.text = in.readString(this.text instanceof Utf8 ? (Utf8)this.text : null);
          break;

        case 2:
          this.label = com.microservices_demo.kafka.avro.model.TweetLabelAvroModel.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










